#!/usr/bin/env sh

battery=/sys/class/power_supply/BAT0

capacity=$(cat "$battery"/capacity) || exit
status=$(cat "$battery"/status)

if [ "$capacity" -ge 75 ]; then
	color="#00ff00"
	bat=""
elif [ "$capacity" -ge 50 ]; then
	color="#ffffff"
	bat=""
elif [ "$capacity" -ge 25 ]; then
	color="#ffff00"
	bat=""
else
	color="#ff0000"
	warn="❗"
	bat=""
	[ "$status" = "Discharging" ] && dunstify -a "Battery" " Low Battery\n Plugin Charger"
fi

[ -z $warn ] && warn=" "

[ "$status" = "Charging" ] && color="#ffffff"

printf "<span color='%s'>%s%s</span>%s\n" "$color" "$(echo "$status" | sed "s/,//;s/Discharging/$bat/;s/Not charging/🛑/;s/Charging/🔌/;s/Unknown/♻️/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"
