#!/usr/bin/env sh

battery=/sys/class/power_supply/BAT0

capacity=$(cat "$battery"/capacity) || exit
status=$(cat "$battery"/status)

if [ "$capacity" -ge 75 ]; then
	color="#00ff00"
elif [ "$capacity" -ge 50 ]; then
	color="#ffffff"
elif [ "$capacity" -ge 25 ]; then
	color="#ffff00"
else
	color="#ff0000"
	warn="❗"
fi

[ -z $warn ] && warn=" "

[ "$status" = "Charging" ] && color="#ffffff"

printf "<span color='%s'>%s%s%s</span>\n" "$color" "$(echo "$status" | sed "s/,//;s/Discharging/🔋/;s/Not charging/🛑/;s/Charging/🔌/;s/Unknown/♻️/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"
