#!/bin/bash
# File              : volume
# Author            : Samyak Puri <samyakpuri@hotmail.com>
# Date              : 07.07.2018
# Last Modified Date: 07.07.2018
# Last Modified By  : Samyak Puri <samyakpuri@hotmail.com>

case $BLOCK_BUTTON in
	1) $TERMINAL -e pulsemixer & disown ;;
	3) pamixer -t ;;
	4) pamixer -i 5 ;;
	5) pamixer -d 5 ;;
esac

[[ $(pamixer --get-mute) = "true" ]] && echo -n 🔇 && exit

echo 🔊 $(pamixer --get-volume)%
