#!/bin/sh
# File              : pacman
# Author            : Samyak Puri <samyakpuri@hotmail.com>
# Date              : 07.07.2018
# Last Modified Date: 02.04.2020

pacman -Qu | wc -l | sed "s/^/📦/;s/^📦0$//g"
