#!/bin/env bash
# File              : demnumount
# Author            : Samyak Puri <samyakpuri@hotmail.com>
# Date              : 17.08.2018
# Last Modified Date: 04.04.2020
# Summary           : A script for mounting drives and creating symlinks to it in home dir, requires udisks2 to work

pgrep -x dmenu && exit

asktype() { \
	case $(printf "USB\\nAndroid" | dmenu -i -p "Mount a USB drive or Android device?") in
		USB) mountusb ;;
		Android) mountandroid ;;
	esac
	}

mountusb() {
	if [ "$(echo "$usbdrives" | wc -l)" -eq 1 ];then
		chosen="$(echo "$usbdrives" | awk '{print $1}')"
	else
		chosen="$(echo "$usbdrives" | dmenu -i -p "Select drive to mount: " | awk '{print $1}')"
	fi
	[ -z "$chosen" ] && exit 1

	mp="$(udisksctl mount -b "$chosen" | cut -d " " -f 4-)"
	if [ -n "$mp" ]; then
	    mp="${mp%?}"
	    link="$(basename "$mp")"
	    ln -s "$mp" "$HOME/$link"
		notify-send "💻 USB mounting" "$chosen mounted to $link."
	fi
}

mountandroid() {
	if [ "$(echo "$android" | wc -l)" -eq 1 ]; then
		read -r chosen name<<< "$android"
	else
		read -r chosen name<<< "$(echo "$android" | dmenu -i -p "Select device to mount: ")"
	fi
	[ -z "$chosen" ] && exit 1

	mp="$HOME/$name"
	mkdir "$mp"
	simple-mtpfs --device "${chosen%?}" "$mp"
	notify-send "🤖 Android Mounting" "Android device mounted to $name."
}

usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | grep -v "nvme0n1" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"
alreadymounted="$(awk '/simple-mtpfs/ {print $2}' /etc/mtab| sed 's#.*/##')"
android="$(simple-mtpfs -l 2>/dev/null | sed 's/ //g')"
android="${android//[[:digit:]]:$alreadymounted/}"

if [ -z "$usbdrives" ]; then
	[ -z "$android" ] && echo "No USB drive or Android device detected" && exit
	echo "Android device(s) detected."
	mountandroid
else
	if [ -z "$android" ]; then
		echo "USB drive(s) detected."
		mountusb
	else
		echo "Mountable USB drive(s) and Android device(s) detected."
		asktype
	fi
fi
