#!/bin/bash
# File              : dmenuumount
# Author            : Samyak Puri <samyakpuri@hotmail.com>
# Date              : 17.08.2018
# Last Modified Date: 03.04.2020

clearup() {
	(rm "$HOME/$1" 2>/dev/null || rmdir "$HOME/$1" 2>/dev/null)&& notify-send "💻 USB unmounting" "$chosen unmounted."
}

mountloc="/run/media/$(whoami)"

drives="$(df -h --output=target | grep "$mountloc" | sed 's#.*/##')" 
android="$(awk '/simple-mtpfs/ {print $2}' /etc/mtab | sed 's#.*/##')"
[ -z "$drives" ] && [ -z "$android" ] && notify-send "No drive to unmount" && exit 1

chosen=$(echo -e "$drives\n$android" | dmenu -i -p "Select drive to unmount: ")
[ -z "$chosen" ] && exit 1

([ "${drives##*"$chosen"*}" ] || udiskie-umount "$mountloc/$chosen" ) && clearup $chosen && exit
([ "${android##*"$chosen"*}" ] || fusermount -u "$HOME/$chosen" ) && clearup $chosen && exit
