#!/bin/sh
# Give dmenu list of all unicode characters to copy from the given file
# Shows the selected character in dunst if running 

# Must have xclip installed to show menu/ needed for copy to clipboard
command -v xclip >/dev/null || (echo "xclip needed for this to function" && exit)

chosen=$(grep -v "#" "$XDG_DATA_HOME/spuri/emoji" | dmenu -i -l 10 -fn Monospace-18)

[ "$chosen" != "" ] || exit 1

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "${c} copied to clipboard." &

s=$(echo "$chosen" | sed "s/.*; //")
echo "$s" | tr -d '\n' | xclip
notify-send "${s} copied to primary." &
