#!/bin/bash
# File              : demnumount
# Author            : Samyak Puri <samyakpuri@hotmail.com>
# Date              : 17.08.2018
# Last Modified Date: 17.08.2018
# Last Modified By  : Samyak Puri <samyakpuri@hotmail.com>
# Summary           : A script for mounting drives and creating symlinks to it in home dir, requires udisks2 to work

pgrep -x dmenu && exit

COLS="name,type,size,mountpoint"

drives="$(lsblk -rpo "$COLS" | grep -v "sda" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"
[ -z "$drives" ] && notify-send "No drive to mount" && exit 1
chosen="$(echo "$drives" | dmenu -i -p "Select drive to mount: " | awk '{print $1}')"
[ -z "$chosen" ] && exit 1
mp=$(udisksctl mount -b "$chosen" | cut -d " " -f 4-)
if [ ! -z "$mp" ]; then
    mp=$(echo ${mp%?})
    link=$(basename "$mp")
    ln -s "$mp" $HOME/"$link"
    notify-send "$link Mounted Succesfully"
fi


