#!/bin/bash

# Bookmark file locations
bmdirs="$HOME/.scripts/bmdirs"
bmfiles="$HOME/.scripts/bmfiles"

# Output locations
shell_shortcuts="$HOME/.shell/shortcuts"
ranger_shortcuts="$HOME/.config/ranger/shortcuts.conf"

# Remove, prepare files
rm -f "$ranger_shortcuts" 2>/dev/null
rm -f "$shell_shortcuts" 2>/dev/null

# Ensure text of argument 1 exists in the file argument 2
ensure() { (grep "$1" "$2")>/dev/null 2>&1 || echo "$1" >> "$2" ;}

ensure "source $HOME/.config/ranger/shortcuts.conf" "$HOME/.config/ranger/rc.conf"

# Format the `bmdirs` file in the correct syntax and sent it to all three configs.
sed "s/#.*$//;/^$/d" "$bmdirs" | tee >(awk '{print "alias " $1"=\"cd "$2" && ls -a\""}' >> "$shell_shortcuts") \
	| awk '{print "map g"$1" cd "$2"\nmap t"$1" tab_new "$2"\nmap m"$1" shell mv -v %s "$2"\nmap Y"$1" shell cp -rv %s "$2}' >> "$ranger_shortcuts"

# Format the `configs` file in the correct syntax and sent it to both configs.
sed "s/#.*$//;/^$/d"  "$bmfiles" | tee >(awk '{print "alias " $1"=\"$EDITOR "$2"\" \\"}' >> "$shell_shortcuts") \
	| awk '{print "map "$1" shell $EDITOR "$2}' >> "$ranger_shortcuts"
